# This is a simple example of a configure.ac file
# This file is used by the autoconf tool to generate a configure script

# The first line is the AC_INIT macro, which is used to initialize the package
# The argument to AC_INIT is the name of the package, and optionally the version number & maintainer
AC_INIT([hello_world], [1.0], [j.percival@imperial.ac.uk])

# The AM_INIT_AUTOMAKE macro is used to initialize the automake package
AM_INIT_AUTOMAKE(subdir-objects)

# The AC_PROG_CC macro is used to check for the C compiler 
AC_PROG_CXX
AC_CONFIG_FILES([Makefile])
AC_OUTPUT